-- Krishi Mitra Supabase PostgreSQL schema
-- Run this in Supabase SQL Editor after creating the project.

create extension if not exists "pgcrypto";

create table if not exists public.market_sources (
  id bigint generated by default as identity primary key,
  name text not null unique,
  url text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.market_prices (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.market_sources(id) on delete cascade,
  observed_on date not null,
  crop text not null,
  market text not null,
  minimum_price numeric,
  maximum_price numeric,
  average_price numeric,
  unit text not null default 'quintal',
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  unique (source_id, observed_on, crop, market)
);

create index if not exists idx_market_prices_crop_date
  on public.market_prices (crop, observed_on desc);

create table if not exists public.farmer_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  village text,
  district text,
  state text,
  latitude double precision,
  longitude double precision,
  land_size_acres numeric,
  soil_type text,
  irrigation_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demand_training_records (
  id bigint generated by default as identity primary key,
  crop text not null,
  observed_on date not null,
  location text,
  soil_type text,
  irrigation_type text,
  land_size_acres numeric,
  input_cost numeric,
  yield_kg numeric,
  market_price numeric,
  demand_score numeric,
  target_profit numeric,
  features_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.demand_recommendations (
  id bigint generated by default as identity primary key,
  farmer_id uuid references public.farmer_profiles(id) on delete cascade,
  crop text not null,
  generated_on date not null,
  expected_price numeric,
  expected_yield_kg numeric,
  estimated_cost numeric,
  estimated_profit numeric,
  confidence numeric,
  explanation text not null,
  model_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.produce_listings (
  id uuid primary key default gen_random_uuid(),
  farmer_id uuid not null references public.farmer_profiles(id) on delete cascade,
  crop text not null,
  quantity_kg numeric not null check (quantity_kg > 0),
  price_per_kg numeric,
  barter_description text,
  quality_grade text,
  harvest_date date,
  location text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.produce_orders (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.produce_listings(id),
  buyer_id uuid not null references public.farmer_profiles(id),
  seller_id uuid not null references public.farmer_profiles(id),
  quantity_kg numeric not null check (quantity_kg > 0),
  settlement_type text not null check (settlement_type in ('cash', 'barter')),
  cash_amount numeric,
  barter_description text,
  status text not null default 'requested',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.storage_facilities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  facility_type text not null,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  capacity_kg numeric,
  price_per_quintal_day numeric,
  accepted_produce text[],
  source text,
  verified_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.storage_bookings (
  id uuid primary key default gen_random_uuid(),
  facility_id uuid not null references public.storage_facilities(id),
  farmer_id uuid not null references public.farmer_profiles(id),
  produce text not null,
  quantity_kg numeric not null,
  start_date date not null,
  end_date date,
  status text not null default 'requested',
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  farmer_id uuid references public.farmer_profiles(id) on delete set null,
  device_id text not null,
  topic text not null,
  reading_type text not null,
  value numeric not null,
  unit text,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_sensor_readings_device_time
  on public.sensor_readings (device_id, recorded_at desc);

insert into public.market_sources (name, url) values
  ('Mumbai APMC', 'https://www.mumbaiapmc.org/en/market-price-en/daily-market-price-en'),
  ('Pune APMC', 'https://apmcpune.in/en/market-price-en/daily-market-price-en'),
  ('Nashik APMC', 'https://apmcnashik.com/')
on conflict (name) do update set url = excluded.url;

alter table public.market_sources enable row level security;
alter table public.market_prices enable row level security;
alter table public.farmer_profiles enable row level security;
alter table public.produce_listings enable row level security;
alter table public.produce_orders enable row level security;
alter table public.storage_facilities enable row level security;
alter table public.storage_bookings enable row level security;
alter table public.sensor_readings enable row level security;

create policy "Anyone can read market sources" on public.market_sources
  for select using (true);
create policy "Anyone can read market prices" on public.market_prices
  for select using (true);
create policy "Anyone can read active listings" on public.produce_listings
  for select using (status = 'active');
create policy "Anyone can read storage facilities" on public.storage_facilities
  for select using (true);

create policy "Farmers manage their profile" on public.farmer_profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Farmers manage their listings" on public.produce_listings
  for all using (auth.uid() = farmer_id) with check (auth.uid() = farmer_id);
create policy "Farmers see their orders" on public.produce_orders
  for select using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "Farmers create orders" on public.produce_orders
  for insert with check (auth.uid() = buyer_id);
create policy "Farmers manage their bookings" on public.storage_bookings
  for all using (auth.uid() = farmer_id) with check (auth.uid() = farmer_id);
create policy "Farmers read their sensor data" on public.sensor_readings
  for select using (auth.uid() = farmer_id);
